### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by T-Wesst** [GideonSamara/MoodGroove#1]
I recommend that you come by either Patrick or me to structure your app.

**Comment by GideonSamara** [comment]
structure meaning what?

**Comment by T-Wesst** [comment]
I noticed you have a backend folder nested inside your assets.
Your backend should be separate from the front end.

example
MoodGroove contains client and server
client  = front end
server = back end

**Comment by GideonSamara** [comment]
oh, okay. I can adjust that

**Comment by T-Wesst** [comment]
So it does not become confusing do the following:

```sh
cd 
cd desktop
mkdir NewMoodGroove
cd NewMoodGroove
npx create-react-app client
mkdir server
echo 'NewMoodGroove'> README.md
git init
git remote add origin <repo link from github here>
cd server && npm init -y
```

If you run into issues let me know and I'll come by.
